#include <QCoreApplication>
#include <QDir>
#include <QFileInfo>
#include <QProcess>
#include <QProcessEnvironment>
#include <QTemporaryDir>
#include <QThread>
#include <QtTest>
#include <iostream>

#include "test_FileAccessService.h"
#include "test_ModelsPathMigration.h"
#include "test_History.h"
#include "test_DownloadInstallService.h"
#include "test_AudioPreviewService.h"
#include "test_ModelsAndRuntimes.h"
#include "test_SttSession.h"
#include "test_StudioCapabilities.h"
#include "test_AlignmentTranscriptMatcher.h"
#include "test_AlignmentWorkflow.h"
#include "test_DubbingProject.h"
#include "test_TranslationProject.h"
#include "test_WorkflowGraph.h"
#include "test_SourceSeparation.h"
#include "test_RuntimeHostProtocol.h"
#include "test_MediaIngestService.h"
#include "test_MediaToolService.h"
#include "test_HardwareManager.h"
#include "test_SubtitleVoice.h"
#include "test_SubtitleOcrPipeline.h"
#include "test_SubtitleOcrController.h"
#include "test_SubtitleOcrRuntimeService.h"
#include "test_TtsTextPreprocessor.h"
#include "test_TtsRequestValidator.h"
#include "test_LlmChatEngine.h"
#include "test_RemoteExecution.h"
#include "test_GatewayTtsRunner.h"
#include "test_ColabTtsRunner.h"
#include "test_ColabVoiceCloneRunner.h"
#include "test_ColabVoiceDesignRunner.h"
#include "test_ColabAlignmentRunner.h"
#include "test_ColabSeparationRunner.h"
#include "test_ColabTranslationRunner.h"
#include "test_ColabSubtitleOcrRunner.h"
#include "test_ColabChatRunner.h"
#include "OcrE2ERunner.h"

#include <QFile>
#include <QTextStream>

int main(int argc, char *argv[])
{
    // This route intentionally bypasses the QtTest child-wrapper: it is a
    // production, headless E2E acceptance runner and its final stdout line is
    // a machine-readable result JSON rather than a QtTest report.
    if (LAStudio::isOcrE2EArtifactReportInvocation(argc, argv))
        return LAStudio::runOcrE2EArtifactReport(argc, argv);
    if (LAStudio::isOcrE2EInvocation(argc, argv))
        return LAStudio::runOcrE2E(argc, argv);

    // QtTest keeps a Windows output handle open until the process terminates.
    // Run the actual suite in a child so this outer runner can print the
    // completed report for CTest, including PASS, FAIL and SKIP evidence.
    if (qEnvironmentVariableIntValue("LASTUDIO_QTEST_CHILD") != 1) {
        const QString requestedSuite = qEnvironmentVariable("LASTUDIO_TEST_SUITE").trimmed();
        const QStringList staleResultFiles = requestedSuite.isEmpty()
            ? QDir::current().entryList({QStringLiteral("*_results.txt")}, QDir::Files)
            : QStringList{requestedSuite + QStringLiteral("_results.txt")};
        // A result generated by an earlier aborted run must never be accepted
        // as evidence for the child we are about to start. These files are
        // test-only reports in the build working directory.
        for (const QString &filename : staleResultFiles) QFile::remove(filename);

        QProcess child;
        QProcessEnvironment childEnvironment = QProcessEnvironment::systemEnvironment();
        childEnvironment.insert(QStringLiteral("LASTUDIO_QTEST_CHILD"), QStringLiteral("1"));
        child.setProcessEnvironment(childEnvironment);
        child.setProcessChannelMode(QProcess::ForwardedChannels);
        child.setWorkingDirectory(QDir::currentPath());
        // Keep an explicitly requested QtTest function when this wrapper
        // starts the isolated child.  Besides making a focused regression
        // reproducible, this avoids having to run an entire slow suite merely
        // to diagnose one process-lifecycle failure.
        QStringList childArguments;
        for (int index = 1; index < argc; ++index)
            childArguments.append(QString::fromLocal8Bit(argv[index]));
        child.start(QFileInfo(QString::fromLocal8Bit(argv[0])).absoluteFilePath(), childArguments);
        if (!child.waitForStarted()) {
            std::cerr << "Failed to start the isolated QtTest runner.\n";
            return 1;
        }
        child.waitForFinished(-1);

        const QStringList resultFiles = requestedSuite.isEmpty()
            ? QDir::current().entryList({QStringLiteral("*_results.txt")}, QDir::Files)
            : QStringList{requestedSuite + QStringLiteral("_results.txt")};
        bool foundResult = false;
        for (const QString &filename : resultFiles) {
            // Windows can report the child as finished just before QtTest's
            // redirected stream becomes visible to a second process. Retry
            // briefly instead of turning a real test result into a false CI
            // failure.
            for (int attempt = 0; attempt < 100; ++attempt) {
                QFile file(filename);
                if (file.open(QIODevice::ReadOnly | QIODevice::Text)) {
                    foundResult = true;
                    QTextStream in(&file);
                    while (!in.atEnd()) std::cout << in.readLine().toStdString() << "\n";
                    file.close();
                    file.remove();
                    break;
                }
                QThread::msleep(50);
            }
        }
        if (!foundResult) {
            std::cerr << "Failed to read the completed QtTest report.\n";
            return 1;
        }
        return child.exitStatus() == QProcess::NormalExit ? child.exitCode() : 1;
    }

    QTemporaryDir testDataDir;
    if (!testDataDir.isValid()) {
        std::cerr << "Failed to create an isolated LA Studio test-data directory.\n";
        return 1;
    }
    qputenv("LASTUDIO_DATA_DIR", testDataDir.path().toUtf8());

    // Ensure that application info is available for tests that use Settings/PathUtils
    QCoreApplication app(argc, argv);
    app.setApplicationName(QStringLiteral("LAStudioUnitTests"));
    app.setOrganizationName(QStringLiteral("LAStudio"));

    int status = 0;
    const QString requestedSuite = qEnvironmentVariable("LASTUDIO_TEST_SUITE").trimmed();

    const QStringList requestedTestArguments = QCoreApplication::arguments().mid(1);
    auto runSuite = [&status, &requestedSuite, &requestedTestArguments](QObject* testObj, const char* name) {
        if (!requestedSuite.isEmpty() && requestedSuite != QString::fromLatin1(name)) {
            return;
        }
        std::cout << "\n==================================================\n";
        std::cout << "Running suite: " << name << "\n";
        std::cout << "==================================================\n";

        const QString filename = QStringLiteral("%1_results.txt").arg(QString::fromLatin1(name));
        QList<QByteArray> localArguments;
        localArguments.append(QByteArrayLiteral("LAStudioUnitTests"));
        for (const QString &argument : requestedTestArguments)
            localArguments.append(argument.toLocal8Bit());
        localArguments.append(QByteArrayLiteral("-o"));
        localArguments.append(filename.toLocal8Bit());
        QVector<char *> localArgv;
        localArgv.reserve(localArguments.size() + 1);
        for (QByteArray &argument : localArguments) localArgv.append(argument.data());
        localArgv.append(nullptr);
        // The parent process reads this report after this child exits; QtTest
        // has then released its Windows file handle.
        const int localArgc = localArguments.size();

        int suiteStatus = QTest::qExec(testObj, localArgc, localArgv.data());
        status |= suiteStatus;
    };

    {
        LAStudio::TestFileAccessService suite;
        runSuite(&suite, "TestFileAccessService");
    }

    {
        LAStudio::TestModelsPathMigration suite;
        runSuite(&suite, "TestModelsPathMigration");
    }

    {
        LAStudio::TestHistory suite;
        runSuite(&suite, "TestHistory");
    }

    {
        LAStudio::TestDownloadInstallService suite;
        runSuite(&suite, "TestDownloadInstallService");
    }

    {
        LAStudio::TestAudioPreviewService suite;
        runSuite(&suite, "TestAudioPreviewService");
    }

    {
        LAStudio::TestModelsAndRuntimes suite;
        runSuite(&suite, "TestModelsAndRuntimes");
    }

    {
        LAStudio::TestSttSession suite;
        runSuite(&suite, "TestSttSession");
    }

    {
        LAStudio::TestStudioCapabilities suite;
        runSuite(&suite, "TestStudioCapabilities");
    }

    {
        LAStudio::TestAlignmentTranscriptMatcher suite;
        runSuite(&suite, "TestAlignmentTranscriptMatcher");
    }

    {
        LAStudio::TestAlignmentWorkflow suite;
        runSuite(&suite, "TestAlignmentWorkflow");
    }

    {
        LAStudio::TestDubbingProject suite;
        runSuite(&suite, "TestDubbingProject");
    }

    {
        LAStudio::TestTranslationProject suite;
        runSuite(&suite, "TestTranslationProject");
    }

    {
        LAStudio::TestWorkflowGraph suite;
        runSuite(&suite, "TestWorkflowGraph");
    }

    {
        LAStudio::TestSourceSeparation suite;
        runSuite(&suite, "TestSourceSeparation");
    }

    {
        LAStudio::TestSubtitleVoice suite;
        runSuite(&suite, "TestSubtitleVoice");
    }

    {
        LAStudio::TestSubtitleOcrPipeline suite;
        runSuite(&suite, "TestSubtitleOcrPipeline");
    }

    {
        LAStudio::TestSubtitleOcrController suite;
        runSuite(&suite, "TestSubtitleOcrController");
    }

    {
        LAStudio::TestSubtitleOcrRuntimeService suite;
        runSuite(&suite, "TestSubtitleOcrRuntimeService");
    }

    {
        LAStudio::TestRuntimeHostProtocol suite;
        runSuite(&suite, "TestRuntimeHostProtocol");
    }

    {
        LAStudio::TestMediaIngestService suite;
        runSuite(&suite, "TestMediaIngestService");
    }

    {
        LAStudio::TestMediaToolService suite;
        runSuite(&suite, "TestMediaToolService");
    }

    {
        LAStudio::TestHardwareManager suite;
        runSuite(&suite, "TestHardwareManager");
    }

    {
        LAStudio::TestTtsTextPreprocessor suite;
        runSuite(&suite, "TestTtsTextPreprocessor");
    }

    {
        LAStudio::TestTtsRequestValidator suite;
        runSuite(&suite, "TestTtsRequestValidator");
    }

    {
        LAStudio::TestLlmChatEngine suite;
        runSuite(&suite, "TestLlmChatEngine");
    }

    {
        LAStudio::TestRemoteExecution suite;
        runSuite(&suite, "TestRemoteExecution");
    }

    {
        LAStudio::TestGatewayTtsRunner suite;
        runSuite(&suite, "TestGatewayTtsRunner");
    }

    {
        LAStudio::TestColabTtsRunner suite;
        runSuite(&suite, "TestColabTtsRunner");
    }
    {
        LAStudio::TestColabTranslationRunner suite;
        runSuite(&suite, "TestColabTranslationRunner");
    }
    {
        LAStudio::TestColabSubtitleOcrRunner suite;
        runSuite(&suite, "TestColabSubtitleOcrRunner");
    }
    {
        LAStudio::TestColabChatRunner suite;
        runSuite(&suite, "TestColabChatRunner");
    }
    {
        LAStudio::TestColabVoiceCloneRunner suite;
        runSuite(&suite, "TestColabVoiceCloneRunner");
    }
    {
        LAStudio::TestColabVoiceDesignRunner suite;
        runSuite(&suite, "TestColabVoiceDesignRunner");
    }
    {
        LAStudio::TestColabAlignmentRunner suite;
        runSuite(&suite, "TestColabAlignmentRunner");
    }
    {
        LAStudio::TestColabSeparationRunner suite;
        runSuite(&suite, "TestColabSeparationRunner");
    }

    std::cout << "\n==================================================\n";
    std::cout << "All test suites completed with status code: " << status << "\n";
    std::cout << "==================================================\n";

    return status;
}
